### ISSUE TITLE
loot progression based on distance from "core" debris

### ISSUE THREAD

**Issue by deltanedas** [Afterlight-3149/afterlight-3149#42]
## Description
maybe have more dangerous wrecks and rocks based on how far you are away from the planet's ex-core

also the new ore vein textures + an upstream pr to make ore veins actually exist to change how common certain ores are at certain "depths" could be cool to make rocks not all be the same

similar story for wrecks, maybe guarded by dragons and stuff, having better loot, machines or being very big as it goes deeper (underground bases of advanced society???)

**Additional context**
i dunno if feature requests go here the issue templates are copy pasted from upstream

also cool fork its very fun

**Comment by moonheart08** [comment]
> ## Description
> 
> maybe have more dangerous wrecks and rocks based on how far you are away from the planet's ex-core
> 
> also the new ore vein textures + an upstream pr to make ore veins actually exist to change how common certain ores are at certain "depths" could be cool to make rocks not all be the same
> 
> similar story for wrecks, maybe guarded by dragons and stuff, having better loot, machines or being very big as it goes deeper (underground bases of advanced society???)
> 
> **Additional context** i dunno if feature requests go here the issue templates are copy pasted from upstream
> 
> also cool fork its very fun

Feature requests go in the discord unless the feature request is from a coder.
